// @implements API-401, FEA-007, BR-104
// On-device meeting summary produced after format, before save. Embedded
// into the transcript markdown so it flows to SQLite + Obsidian without a
// schema change. Generated by `SummarizationService` — either Apple's
// on-device Foundation Models (macOS 26+) or the dependency-free
// `ExtractiveSummarizer` fallback. Never leaves the device (BR-104/BR-101).

import Foundation

public struct MeetingSummary: Codable, Sendable, Equatable {
    /// 1-3 sentence prose overview of the meeting.
    public let overview: String
    /// Key discussion points, one per bullet.
    public let keyPoints: [String]
    /// Action items / follow-ups, one per bullet.
    public let actionItems: [String]
    /// Human-readable label for the engine that produced this summary
    /// (e.g. "Apple Foundation Models" or "Extractive (on-device)").
    /// Surfaced in the rendered markdown footer for transparency.
    public let generator: String

    public init(
        overview: String,
        keyPoints: [String],
        actionItems: [String],
        generator: String
    ) {
        self.overview = overview
        self.keyPoints = keyPoints
        self.actionItems = actionItems
        self.generator = generator
    }

    /// True when there is nothing worth embedding — the orchestrator skips
    /// the markdown prepend in that case so an empty summary block never
    /// lands in the transcript.
    public var isEmpty: Bool {
        overview.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            && keyPoints.isEmpty
            && actionItems.isEmpty
    }
}
